# (c) 2024-2024 Y. Forku
# START: Thu 15 Feb 2024 13:00

PROGRAM=djbx33a

ALL:	$(PROGRAM)

$(PROGRAM): $(PROGRAM).c
	gcc -std=gnu18 -o $(PROGRAM) $(PROGRAM).c

clean:
	rm -f $(PROGRAM)

.phony: ALL clean

