# (c) 2016-2024 BinKadal, Sdn. Bhd.
# REV07: Thu 29 Feb 2024 13:00
# REV06: Tue 15 Nov 2022 07:00
# START: Fri 01 Jan 2016 00:00
# This is a free Makefile configuration.

PROGRAM=cbkadal

ALL:	$(PROGRAM)

$(PROGRAM): $(PROGRAM).c
	gcc -std=gnu18 -o $(PROGRAM) $(PROGRAM).c

clean:
	rm -f $(PROGRAM)

.phony: ALL clean

